workflows:
   android-workflow:
    name: Android workflow
XCODE_PROJECT: "ionic"
XCODE_SCHEME: "ionic"
environment:
      groups:
        # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
      #- keystore_credentials # <-- (Includes KEYSTORE, KEYSTORE_PASSWORD, KEY_ALIAS_PASSWORD, KEY_ALIAS, KEYSTORE_PATH)
        #KEYSTORE :<-- Put your keystore file here
     # KEYSTORE_PASSWORD  <-- Put your keystore password here
     # KEY_ALIAS_PASSWORD <-- Put your keystore alias password here
      #KEY_ALIAS <-- Put your keystore alias username here
      # KEYSTORE_PATH  '/tmp/keystore.keystore'
        - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS - Put your google-services.json here)
        - other
      xcode: 12.4
      node: 12
      npm: 6 
       
cache:
      cache_paths:
        - $FCI_BUILD_DIR/node_modules

triggering:
            events:
                - push
            branch_patterns:
                - pattern: main
                  include: true
                  source: true


scripts:
      
      - name: Install dependencies
        script: |
          npm install
          npm ci
          cvm install 9.0.0
          cvm use 9.0.0
          npm install -g ionic
          ionic info  
            
      - name: Add Android platform
        script: |
          set -x
          ionic cordova platform remove android --nosave
          ionic cordova platform add android --confirm --no-interactive --noresources
      - name: Build Android
        script: |    
          set -x
          set -e
          ionic cordova build android --release --no-interactive --prod --device
          echo $KEYSTORE | base64 --decode > $KEYSTORE_PATH
          UNSIGNED_APK_PATH=$(find platforms/android/app/build/outputs -name "*.apk" | head -1)
          jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore "${KEYSTORE_PATH}" -storepass "${KEYSTORE_PASSWORD}" -keypass "${KEY_ALIAS_PASSWORD}" "${UNSIGNED_APK_PATH}" "${KEY_ALIAS}"
          mv $UNSIGNED_APK_PATH $(echo $UNSIGNED_APK_PATH | sed 's/-unsigned//')
artifacts:
      - platforms/android/app/build/outputs/**/*.apk
      - platforms/android/app/build/outputs/**/mapping.txt                   
      
publishing:
        # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
        email:
            recipients:
                - developer3iwaju@gmail.com
                - mouftaouhanane@gmmail.com
            notify :
              success: true     # To not receive a notification when a build succeeds
              failure: false    # To not receive a notification when a build fails    
           
         